<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post list item template
 *
 * @var $block \Magefan\Blog\Block\Post\AbstractPost
 */
?>
<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
?>
<li class="post-holder post-holder-<?php echo $_post->getId() ?>">
    <div class="row">
        <div class="col-sm-5 ">
            <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
                <div class="post-ftimg-hld">
                    <a href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
                        <img src="<?php echo $featuredImage ?>" alt="<?php echo $_postName ?>" />
                    </a>
                </div>
            <?php } ?>
        </div>
        <div class="col-sm-7">
            <h2 class="post-title">
                <a class="post-item-link"
                   href="<?php echo $_postUrl ?>">
                    <?php echo $_postName; ?>
                </a>
            </h2>
            <div class="post-top clearfix">
                <div class="post-info left-block">
					<div class="comments">
						<a title="<?php echo $block->escapeHtml($_post->getTitle()) ?>" href="<?php echo $_postUrl ?>#post-comments">
							<?php echo $block->escapeHtml($_post->getCommentsCount()) ?><?php echo __(' Comments') ?>
						</a>
					</div>
					<?php if ($_categoriesCount = $_post->getCategoriesCount()) { ?>
						<div class="post-category">
							<?php echo __('Posted in') ?>
							<?php $n = 0; foreach($_post->getParentCategories() as $ct) { $n++; ?>
								<a title="<?php echo $block->escapeHtml($ct->getTitle()) ?>" href="<?php echo $ct->getCategoryUrl() ?>">
									<?php echo $block->escapeHtml($ct->getTitle()) ?>
								</a>
								<?php if ($n != $_categoriesCount) { ?>, <?php } ?>
							<?php } ?>
						</div>
					<?php } ?>
                    <?php if ($_author = $_post->getAuthor()) { ?>
                        <div class="post-author">                                           
                            <?php echo __('By ') ?>
                            <span><?php echo $block->escapeHtml($_author->getTitle()) ?></span>
                        </div>
                    <?php } ?>
                </div>
                <div class="post-date right-block">
                    <span class="value"><?php echo $_post->getPublishDate('F d, Y') ?></span>
                </div>
            </div>
            <div class="postContent">
                <?php echo $block->getShorContent($_post) ?>
            </div>
            <div class="postBookmarks">
                <span class="label"><?php echo __('Share post: ') ?></span>
                <div class="addthis_toolbox addthis_default_style"
                    addthis:url="<?php echo $_postUrl ?>"
                    addthis:title="<?php echo $_postName; ?>"
                    <?php if ($firstImage = $_post->getFirstImage()) { ?>
                    addthis:media="<?php echo $firstImage ?>"
                    <?php } ?>>
                    <a class="addthis_button_facebook"></a>
                    <a class="addthis_button_twitter"></a>
                    <a class="addthis_button_email"></a>
                    <a class="addthis_button_compact"></a>
                </div>
            </div>
            <?php if ($_tagsCount = $_post->getTagsCount()) { ?>
                <div class="tags-wrapper">
                    <h4><?php echo __('Tags:') ?></h4>
                    <ul class="tags">                    
                        <?php $n = 0; foreach($_post->getRelatedTags() as $tag) { $n++; ?>
                        <li>
                            <a title="<?php echo $block->escapeHtml($tag->getTitle()) ?>" href="<?php echo $tag->getTagUrl() ?>">
                                <?php echo $block->escapeHtml($tag->getTitle()) ?>
                            </a>
                        </li>
                        <?php } ?>
                    </ul>
                </div>
            <?php } ?>
            <div class="actions">
                <a class="btn btn-default" href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
                   <?php echo __('Read More') ?>
                </a>
            </div>
        </div>
    </div>
</li>