<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post view template
 *
 * @var $block \Magefan\Blog\Block\Post\View
 */
?>
<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
?>
<div class="post-view">
    <div class="postWrapper">
        <div class="postTitle clearfix">
            <div class="postDetails pull-left">
                <?php $_categoriesCount = $_post->getCategoriesCount(); ?>
                <?php if (!empty($_categoriesCount)): ?>
                    <?php echo __('Posted in') ?>
                    <?php $n = 0; foreach($_post->getParentCategories() as $ct) { $n++; ?>
                        <a title="<?php echo $block->escapeHtml($ct->getTitle()) ?>" href="<?php echo $ct->getCategoryUrl() ?>">
                            <?php echo $block->escapeHtml($ct->getTitle()) ?>
                        </a>
                        <?php if ($n != $_categoriesCount) { ?>, <?php } ?>
                    <?php } ?>
                <?php else: ?>
                    <?php echo __('Posted') ?>
                <?php endif; ?>
                &nbsp;&nbsp;|&nbsp;&nbsp;
                <?php echo __("By"); ?> <h4 class="poster"> <?php if ($_author = $_post->getAuthor()) { ?><?php echo $block->escapeHtml($_author->getTitle()) ?>
                <?php } ?></h4>
            </div>
            <small class="pull-right"><?php echo $_post->getPublishDate('F d, Y') ?></small>
        </div>
        <div class="postContent">
            <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
                <div class="post-ftimg-hld">
                    <img src="<?php echo $featuredImage ?>" alt="<?php echo $_postName ?>" />
                </div>
            <?php } ?>
            <?php echo $block->getContent() ?>
        </div>
        <div class="postBookmarks">
            <h4><?php echo __('Share post:') ?></h4>
            <div class="addthis_toolbox addthis_default_style" addthis:url="<?php echo $_postUrl ?>">
                <a class="addthis_button_facebook"><?php echo __('Facebook') ?></a>
                <a class="addthis_button_twitter"><?php echo __('Twitter') ?></a>
                <a class="addthis_button_google_plusone"><?php echo __('Google Plus') ?></a>
            </div>        
        </div>
        <?php if ($_tagsCount = $_post->getTagsCount()) { ?>
            <div class="tags-wrapper">
                <h4><?php echo __('Tags:') ?></h4>
                <ul class="tags">                    
                    <?php $n = 0; foreach($_post->getRelatedTags() as $tag) { $n++; ?>
                    <li>
                        <a title="<?php echo $block->escapeHtml($tag->getTitle()) ?>" href="<?php echo $tag->getTagUrl() ?>">
                            <?php echo $block->escapeHtml($tag->getTitle()) ?>
                        </a>
                    </li>
                    <?php } ?>
                </ul>
            </div>
        <?php } ?>
    </div>
    <div class="post-bottom">
        <?php echo $this->getChildHtml('blog.post.bottom') ?>
    </div>
</div>